export const paymentMethod = {
    "101": "Credit Card",
    "305": "Rakuten Pay (Online Payment)",
    "306": "Paypal",
    "307": "Yahoo! Wallet payment Digicon version",
    "309": "Recruit Easy Payment",
    "310": "LINE Pay",
    "311": "PayPay (Online Payment)",
    "313": "Wallet payment service (Type-Y)",
    "314": "Melpay Net Payment",
    "315": "Amazon Pay",
    "316": "Epos Easy Settlement",
    "401": "Docomo Payment (carrier)",
    "402": "au Easy settlement",
    "405": "SoftBank Collective Payment (B)",
    "406": "au PAY (net payment)",
    "510": "Alipay International Payment",
    "513": "JCB PREMO payment / house prepaid payment",
    "514": "UnionPay Net Payment",
    "601": "Apple Pay",
    "604": "Google Pay",
    "701": "Convenience payment",
    "702": "Comprehensive transfer settlement",
    "703": "Pay-easy payment",
    "710": "NP Deferred Payment",
    "805": "Permanent Immortal Point Settlement",
    "806": "T point program (online payment)",
    "912": "Maillink type",
    "999": "Common",
};
export const paymentTypeError = {
    "101": {
        "00": "XML format invalid",
        "01": "Invalid payment method",
        "02": "Invalid API request ID",
        "03": "No value is specified for the required field",
        "04": "Data type other than storable data type is specified",
        "05": "Exceeding data length",
        "06": "Illegal format",
        "07": "Definition value error",
        "08": "-",
        "09": "Invalid request hash value",
        "10": "Submitted request expires (default 10 minutes)",
        "11": "No settlement associated with the specified processing target SBPS transaction ID",
        "12": "No settlement associated with the processing target tracking ID specified in the recredit.",
        "13": "Value is set for a parameter that cannot be specified in recredit.",
        "14": "Merchant ID / service ID does not exist",
        "20": "Credit card fraud card filter error",
        "21": "Credit center error",
        "22": "Credit card usage limit exceeded",
        "23": "Credit card not accepted",
        "24": "Illegal PIN",
        "25": "Exceeded credit card usage limit",
        "26": "Credit card not accepted",
        "27": "Credit card number / expiration date error",
        "28": "Transaction details cannot be handled",
        "29": "Cannot use the specified bonus number of times",
        "30": "Not available for designated bonus month",
        "31": "Specified bonus amount is not available",
        "32": "Not available in the designated payment start month",
        "33": "Cannot be used for the specified number of divisions",
        "34": "Specified installment amount not available",
        "35": "Specified initial payment amount is not available",
        "36": "Other credit errors",
        "37": "No sales request is required because automatic sales are set.",
        "38": "In the case of G formula, please process the sales with a file.",
        "39": "Sales processing has been canceled because there is no credit result.",
        "40": "Sales processing has been canceled because the credit has been cancelled.",
        "41": "Processing has been canceled because sales processing has been completed.",
        "42": "The processing date and time of sales processing is from the credit date3Valid until the end of the month.",
        "43": "In the case of G type, please process the refund with a file.",
        "44": "Refund processing has been canceled because the credit result does not exist.",
        "45": "Refund processing has been canceled because the credit has been cancelled.",
        "46": "Refund processing has been canceled because refund processing has been completed.",
        "47": "Refund processing has been canceled due to continuous billing.",
        "48": "-",
        "49": "Request a refund for automatic sales API",
        "50": "For P expressions, use the refund request API.",
        "51": "The credit cancellation process has been canceled because the credit result does not exist.",
        "52": "Since the credit has been canceled, the credit cancellation process has been cancelled.",
        "53": "-",
        "54": "Credit cancellation processing has been canceled due to continuous billing.",
        "55": "-",
        "56": "Refunds will be processed after the sales date and from the credit cancellation date.3Valid until the end of the month.",
        "57": "The specified renewal billing has already been cancelled.",
        "58": "Continuous billing in-use error",
        "59": "In the case of automatic sales (applying the commit flag), please perform refund processing after executing the commit.",
        "60": "Commit (cancel) cannot be executed because the process has already been completed.",
        "61": "Incorrect security code",
        "62": "-",
        "63": "Authentication assist information required error (SmartLinkTarget when using)",
        "64": "SmartLinkCenter error (SmartLinkTarget when using)",
        "65": "Settlement company judgment error",
        "66": "Settlement company judgment error",
        "67": "Settlement company judgment error",
        "68": "Settlement company judgment error",
        "69": "Settlement company judgment error",
        "70": "Settlement company judgment error",
        "71": "Settlement company judgment error",
        "72": "Settlement company judgment error",
        "73": "Settlement company judgment error",
        "74": "Settlement company judgment error",
        "75": "Settlement company judgment error",
        "76": "Settlement company judgment error",
        "77": "Settlement company judgment error",
        "78": "Credit card information storage flag specification error",
        "79": "Sales processing has been canceled because the specified amount exceeds the credit time amount.",
        K0: "Partial refund processing has been canceled because sales processing has not been carried out.",
        K1: "The partial refund process has been canceled because the total refund amount exceeds the sales amount.",
        K2: "Settlement company judgment error",
        K3: "Credit card brand return flag specification error",
        K4: "The credit information change process has been canceled.",
        K5: "The credit information change process has been canceled.",
        W0: "Sales processing has been canceled because the cancellation process is already in progress.",
        W1: "For the processing date and time, specify a date after the credit date.",
        W2: "Refund processing has been canceled because sales processing has not been carried out.",
        W3: "Refund processing has been canceled because refund processing is already in progress.",
        W4: "Refund processing has been canceled because the specified amount exceeds the sales amount.",
        W5: "For the processing date and time, specify a date after the sales date.",
        W6: "The cancellation process has been canceled because the cancellation process is already in progress.",
        "80": "GW system error",
        "81": "API request parameter error",
        "82": "-",
        "83": "GW record search error",
        "84": "Settlement company response parameter error",
        "85": "Settlement company connection error",
        "86": "Settlement company system error",
        "90": "API system error",
        "91": "-",
        "92": "GW connection error",
        "93": "Maximum number of re-entry limit error",
        "94": "Settlement incomplete error",
        "95": "Customer information integrity error",
        "96": "Double request error",
        "97": "Double request error (multiple partial refunds)",
        "98": "Permanent token integrity error",
    },
};

export const paymentItemError = {
    "000": "API request ID",
    "001": "Merchant ID",
    "002": "Service ID",
    "003": "Customer ID",
    "004": "Purchase ID",
    "005": "Product ID",
    "006": "Product name",
    "007": "Tax amount",
    "008": "Amount (tax included)",
    "009": "Result notification destination CGI",
    "010": "Free column 1",
    "011": "Free column 2",
    "012": "Free column 3",
    "013": "Billing number",
    "014": "Line number",
    "015": "Item ID",
    "016": "Item name",
    "017": "Detail quantity",
    "018": "Detailed tax amount",
    "019": "Detailed amount (tax included)",
    "020": "Payment classification",
    "021": "Last billing month",
    "022": "Campaign type",
    "023": "Request date and time",
    "024": "Request permissible time",
    "025": "Hash",
    "026": "SBPS transaction ID to be processed",
    "027": "Processing target tracking ID",
    "028": "3DES encryption flag",
    "029": "Processing date and time",
    "030": "SBPS customer information return flag",
    "101": {
        "200": "Credit Card Number",
        "201": "Credit card expiration date",
        "202": "Transaction classification",
        "203": "Number of divisions",
        "204": "Number of bonus combinations",
        "205": "Credit card information storage flag",
        "206": "Remarks column 1",
        "207": "Remarks column 2",
        "208": "Remarks column 3",
        "209": "Security code",
        "210": "-",
        "211": "-",
        "212": "-",
        "213": "-",
        "214": "Payment information usage specific type",
        "215": "Payment payment method usage specific type",
        "216": "Input information return type at the time of payment",
        "217": "Credit card brand return flag",
        "218": "-",
        "219": "-",
        "220": "-",
        "221": "-",
        "222": "-",
        "223": "-",
        "224": "-",
        "225": "Refund branch number",
        "226": "-",
        "227": "Token",
        "228": "Token key",
        "229": "Permanent token",
        "900": "-",
    },
};
